name: Tests CI

on: [push, pull_request]

jobs:
  server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - uses: actions/checkout@v2
      - name: Test server using Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install
      - run: yarn test
  
  client:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v2
      - name: Test client using Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install
      - run: yarn test